flowchart TD
    A(MissionComponent) -->|Actor Component| B(Player Character)
    C[DataAsset] --> D[Holds Mission Data.]
    E(View Model Class) --> |Holds Data to be Used by UI| F(W/WBPMission Display)

sequenceDiagram 
    participant p